### ISSUE TITLE
Unexpected non-empty log failed to read the last block

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#3543]
**Description**
On running qa tests I saw after test start the following logs.

```
09:00:58.927 [] [main] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [10/10]: zeebe partitions
09:00:58.929 [] [main] INFO  io.zeebe.broker.system - Bootstrap Broker-0 partitions [1/1]: partition 1
09:00:58.960 [Broker-0-ZeebePartition-1] [0.0.0.0:25602-zb-actors-1] WARN  io.zeebe.logstreams - Unexpected non-empty log failed to read the last block
09:00:58.972 [GatewayTopologyManager] [0.0.0.0:25602-zb-actors-1] DEBUG io.zeebe.gateway - Received metadata change from Broker 0, partitions {} and terms {}.
09:00:58.974 [GatewayTopologyManager] [0.0.0.0:25602-zb-actors-1] INFO  io.zeebe.transport.endpoint - Registering endpoint for node '0' with address '0.0.0.0:25602' on transport 'gateway-broker-client'
09:00:58.980 [io.zeebe.logstreams.impl.log.LogStreamImpl] [0.0.0.0:25602-zb-actors-0] WARN  io.zeebe.logstreams - Unexpected non-empty log failed to read the last block
```

This doesn't make sense to me

**Comment by npepinpe** [comment]
Also not to me :sweat_smile: The idea is that we check before if the log is empty, and if so we return -1; if not, then we should be able to always read the last block, since non-empty means at least one block is there. Sounds like a bug to me, I'll investigate.

**Comment by Zelldon** [comment]
thanks @npepinpe :+1:

**Comment by npepinpe** [comment]
Alright, it's not a big problem as far as I can tell. It's a mismatch from when we migrated the log; the new implementation of `getFirstBlockAddress` is wrong and does not return a negative address if the log is empty. So we should fix it but it's not a production issue.

**Comment by npepinpe** [comment]
Blocked by [zeebe-io/atomix#125](https://github.com/zeebe-io/atomix/pull/125).

**Comment by Zelldon** [comment]
Shouldn't this be fixed? I still see this in our logs and when I start the current 0.22.0 release.

```
2020-01-14 07:42:12.900 [] [main] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [7/11]: cluster services
2020-01-14 07:42:14.127 [] [main] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [8/11]: topology manager
2020-01-14 07:42:14.128 [] [main] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [9/11]: metric's server
2020-01-14 07:42:14.156 [] [main] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [10/11]: leader management request handler
2020-01-14 07:42:14.158 [] [main] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [11/11]: zeebe partitions
2020-01-14 07:42:14.161 [] [main] INFO  io.zeebe.broker.system - Bootstrap Broker-0 partitions [1/1]: partition 1
2020-01-14 07:42:14.199 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-0] WARN  io.zeebe.logstreams - Unexpected non-empty log failed to read the last block
2020-01-14 07:42:14.220 [io.zeebe.logstreams.impl.log.LogStreamImpl] [Broker-0-zb-actors-1] WARN  io.zeebe.logstreams - Unexpected non-empty log failed to read the last block
2020-01-14 07:42:18.865 [partition-1-processor] [Broker-0-zb-actors-0] INFO  io.zeebe.logstreams - Recovered state of partition 1 from snapshot at position -1
```
