### ISSUE TITLE
Gateway communicated with broker in different cluster

### ISSUE THREAD

**Issue by MiguelPires** [zeebe-io/zeebe#5641]
**Describe the bug**
The benchmark for the 0.25 release went down today (20/10) at around 03:14 when broker 2 restarted and broker 0 and 1 got stuck in an election loop. It seems like 0 and 1 are not able to communicate so one broker starts an election and is elected until, eventually the other broker starts another election because it doesn't get heartbeats. More or less around this time this was logged several times:
```{
  "insertId": "18omypxf3ou7ul",
  "jsonPayload": {
    "message": "Received invalid handshake, closing connection",
    "thread": "netty-messaging-event-epoll-client-9",
    "logger": "io.atomix.cluster.messaging.impl.NettyMessagingService",
```
Hours later the loop stops and both 0 and 1 believe they're leader.

Getting the topology from the gateway returns the following:
```
Cluster size: 3
Partitions count: 3
Replication factor: 3
Gateway version: 0.25.0-SNAPSHOT
Brokers:
  Broker 1 - release-0-24-4-rc2-zeebe-1.release-0-24-4-rc2-zeebe.release-0-24-4-rc2.svc.cluster.local:26501
    Version: 0.24.4
    Partition 1 : Follower
    Partition 2 : Follower
    Partition 3 : Leader
```

This indicates that the gateway in the `release-0-25-0` namespace is communicating with a broker in the `relase-0-24-4-rc2` namespace. It also explains the `invalid handshake` log statement, since that is logged when a preamble in the message is different from what the NettyMessagingService expects. This preamble is the hashcode of the clusterName which is based on the version (e.g., "release-0-25-0-zeebe"), so they're different in different namespaces.
The `release-0-24-4` cluster is also down.

**Comment by Zelldon** [comment]
```
[zell zeebe/ ns:release-0-25-0]$ kgpo
NAME                                            READY   STATUS      RESTARTS   AGE
curator-1603162800-gtpp7                        0/1     Completed   0          13h
elasticsearch-master-0                          1/1     Running     0          29h
elasticsearch-master-1                          1/1     Running     0          6d2h
elasticsearch-master-2                          1/1     Running     0          6d2h
release-0-25-0-zeebe-0                          1/1     Running     0          6d2h
release-0-25-0-zeebe-1                          1/1     Running     0          6d2h
release-0-25-0-zeebe-2                          0/1     Running     0          6d2h
release-0-25-0-zeebe-gateway-649c746586-kxfgj   1/1     Running     0          6d2h
starter-7978d6bdcc-vvtzs                        1/1     Running     0          6d2h
worker-6bf97dfc5-2gcfc                          1/1     Running     0          43h
worker-6bf97dfc5-j59b6                          1/1     Running     0          6d2h
worker-6bf97dfc5-kjh9l                          1/1     Running     0          6d2h
worker-6bf97dfc5-lldqm                          1/1     Running     0          6d2h
worker-6bf97dfc5-ltwx2                          1/1     Running     0          6d2h
worker-6bf97dfc5-lx62h                          1/1     Running     0          6d2h
worker-6bf97dfc5-lzwd4                          1/1     Running     0          6d2h
worker-6bf97dfc5-q8z9v                          1/1     Running     0          6d2h
worker-6bf97dfc5-qqndt                          1/1     Running     0          6d2h
worker-6bf97dfc5-t7q6p                          1/1     Running     0          6d2h
worker-6bf97dfc5-wdq6h                          1/1     Running     0          6d2h
worker-6bf97dfc5-zg4s6                          1/1     Running     0          29h
[zell zeebe/ ns:release-0-25-0]$ k exec -it release-0-25-0-zeebe-gateway-649c746586-kxfgj -- bash
root@release-0-25-0-zeebe-gateway-649c746586-kxfgj:/usr/local/zeebe# zbctl status
Error: rpc error: code = Unavailable desc = connection error: desc = "transport: authentication handshake failed: tls: first record does not look like a TLS handshake"
root@release-0-25-0-zeebe-gateway-649c746586-kxfgj:/usr/local/zeebe# zbctl status --insecure
Cluster size: 3
Partitions count: 3
Replication factor: 3
Gateway version: 0.25.0-SNAPSHOT
Brokers:
  Broker 1 - release-0-24-4-rc2-zeebe-1.release-0-24-4-rc2-zeebe.release-0-24-4-rc2.svc.cluster.local:26501
    Version: 0.24.4
    Partition 1 : Follower
    Partition 2 : Follower
    Partition 3 : Follower
root@release-0-25-0-zeebe-gateway-649c746586-kxfgj:/usr/local/zeebe# 
```

How is this possible :scream:

**Comment by Zelldon** [comment]
Checked the pods hostnames:

```
[zell zeebe/ ns:release-0-25-0]$ k exec -it release-0-25-0-zeebe-gateway-649c746586-kxfgj -- bash
root@release-0-25-0-zeebe-gateway-649c746586-kxfgj:/usr/local/zeebe# host
hostid    hostname  
root@release-0-25-0-zeebe-gateway-649c746586-kxfgj:/usr/local/zeebe# hostname 
release-0-25-0-zeebe-gateway-649c746586-kxfgj
root@release-0-25-0-zeebe-gateway-649c746586-kxfgj:/usr/local/zeebe# exit
exit
[zell zeebe/ ns:release-0-25-0]$ k exec -it release-0-25-0-zeebe-0 -- bash
root@release-0-25-0-zeebe-0:/usr/local/zeebe# hostname 
release-0-25-0-zeebe-0
root@release-0-25-0-zeebe-0:/usr/local/zeebe# exit
exit
[zell zeebe/ ns:release-0-25-0]$ k exec -it release-0-25-0-zeebe-1 -- bash
root@release-0-25-0-zeebe-1:/usr/local/zeebe# hostname
release-0-25-0-zeebe-1
root@release-0-25-0-zeebe-1:/usr/local/zeebe# exit
exit
[zell zeebe/ ns:release-0-25-0]$ k exec -it release-0-25-0-zeebe-2 -- bash
root@release-0-25-0-zeebe-2:/usr/local/zeebe# hostname
release-0-25-0-zeebe-2
root@release-0-25-0-zeebe-2:/usr/local/zeebe# 
```

Configmap:

```
[zell zeebe/ ns:release-0-25-0]$ k describe configmaps 
curator-config                release-0-25-0-zeebe-cluster  
[zell zeebe/ ns:release-0-25-0]$ k describe configmaps release-0-25-0-zeebe-cluster
Name:         release-0-25-0-zeebe-cluster
Namespace:    release-0-25-0
Labels:       app.kubernetes.io/instance=release-0-25-0
              app.kubernetes.io/managed-by=Helm
              app.kubernetes.io/name=zeebe-cluster
Annotations:  <none>

Data
====
application.yaml:
----

broker-log4j2.xml:
----

gateway-log4j2.xml:
----

startup.sh:
----
#!/usr/bin/env bash
set -eux -o pipefail

export ZEEBE_BROKER_NETWORK_ADVERTISEDHOST=${ZEEBE_BROKER_NETWORK_ADVERTISEDHOST:-$(hostname -f)}
export ZEEBE_BROKER_CLUSTER_NODEID=${ZEEBE_BROKER_CLUSTER_NODEID:-${K8S_POD_NAME##*-}}

# As the number of replicas or the DNS is not obtainable from the downward API yet,
# defined them here based on conventions
export ZEEBE_BROKER_CLUSTER_CLUSTERSIZE=${ZEEBE_BROKER_CLUSTER_CLUSTERSIZE:-1}
contactPointPrefix=${K8S_POD_NAME%-*}
contactPoints=${ZEEBE_BROKER_CLUSTER_INITIALCONTACTPOINTS:-""}
if [[ -z "${contactPoints}" ]]; then
  for ((i=0; i<${ZEEBE_BROKER_CLUSTER_CLUSTERSIZE}; i++))
  do
    contactPoints="${contactPoints},${contactPointPrefix}-$i.$(hostname -d):26502"
  done

  export ZEEBE_BROKER_CLUSTER_INITIALCONTACTPOINTS="${contactPoints}"
fi

if [ "$(ls -A /exporters/)" ]; then
  mkdir /usr/local/zeebe/exporters/
  cp -a /exporters/*.jar /usr/local/zeebe/exporters/
else  
  echo "No exporters available."
fi

exec /usr/local/zeebe/bin/broker

Events:  <none>
```

**Comment by Zelldon** [comment]
Found the same [log](https://console.cloud.google.com/logs/viewer?interval=JUMP_TO_TIME&authuser=1&project=zeebe-io&minLogLevel=0&expandAll=false&timestamp=2020-10-20T00:53:21.857000000Z&customFacets=&limitCustomFacetWidth=true&advancedFilter=resource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22zeebe-io%22%0Aresource.labels.location%3D%22europe-west1-b%22%0Aresource.labels.cluster_name%3D%22zeebe-cluster%22%0Aresource.labels.namespace_name%3D%22release-0-25-0%22%0Alabels.k8s-pod%2Fapp_kubernetes_io%2Fcomponent%3D%22gateway%22%0Alabels.k8s-pod%2Fapp_kubernetes_io%2Finstance%3D%22release-0-25-0%22%0Alabels.k8s-pod%2Fapp_kubernetes_io%2Fmanaged-by%3D%22Helm%22%0Alabels.k8s-pod%2Fapp_kubernetes_io%2Fname%3D%22zeebe-cluster%22%0ANOT%20jsonPayload.exception:%22io.zeebe.gateway.impl.broker.RequestRetriesExhaustedException:%20Expected%20to%20execute%20the%20command%20on%20one%20of%20the%20partitions,%20but%20all%20failed;%22%0AjsonPayload.message!%3D%22Expected%20to%20handle%20gRPC%20request,%20but%20an%20unexpected%20error%20occurred%22%0AjsonPayload.message!%3D%22Expected%20to%20handle%20gRPC%20request,%20but%20request%20timed%20out%20between%20gateway%20and%20broker%22%0AjsonPayload.message!%3D%22Failed%20to%20activate%20jobs%20for%20type%20benchmark-task%20from%20partition%202%22%0AjsonPayload.message!%3D%22Remove%20blocking%20request%20BrokerActivateJobsRequest%7BrequestDto%3D%7B%5C%22type%5C%22:%5C%22benchmark-task%5C%22,%5C%22worker%5C%22:%5C%22benchmark-worker%5C%22,%5C%22timeout%5C%22:300,%5C%22maxJobsToActivate%5C%22:120,%5C%22jobKeys%5C%22:%5B%5D,%5C%22jobs%5C%22:%5B%5D,%5C%22variables%5C%22:%5B%5D,%5C%22truncated%5C%22:false%7D%7D%20for%20job%20type%20benchmark-task%20after%20timeout%20of%20PT1M2S%22%0AjsonPayload.message!%3D%22Failed%20to%20activate%20jobs%20for%20type%20benchmark-task%20from%20partition%203%22&scrollTimestamp=2020-10-20T01:15:31.544385000Z&dateRangeEnd=2020-10-20T01:53:21.857Z&dateRangeUnbound=backwardInTime&pinnedLogId=h7p58bg21zm4gr&pinnedLogTimestamp=2020-10-20T01:14:38.264600Z) in the Gateway, regarding invalid handshake:

```

2020-10-20 03:14:38.264 CEST
Received invalid handshake, closing connection
 
Expand all | Collapse all{
 insertId: "h7p58bg21zm4gr"  
 jsonPayload: {
  context: {…}   
  logger: "io.atomix.cluster.messaging.impl.NettyMessagingService"   
  message: "Received invalid handshake, closing connection"   
  serviceContext: {…}   
  thread: "netty-messaging-event-epoll-client-1"   
 }
 labels: {…}  
 logName: "projects/zeebe-io/logs/zeebe-cluster"  
 receiveTimestamp: "2020-10-20T01:14:55.477340710Z"  
 resource: {…}  
 severity: "WARNING"  
 sourceLocation: {…}  
 timestamp: "2020-10-20T01:14:38.264600Z"  
}
```

**Comment by Zelldon** [comment]
[Kube events:](https://console.cloud.google.com/logs/viewer?interval=JUMP_TO_TIME&authuser=1&project=zeebe-io&minLogLevel=0&expandAll=false&timestamp=2020-10-20T01:11:02.677000000Z&customFacets=&limitCustomFacetWidth=true&advancedFilter=%0AjsonPayload.kind%3D%22Event%22&scrollTimestamp=2020-10-20T01:29:47.000000000Z&dateRangeStart=2020-10-20T00:11:02.677Z&dateRangeEnd=2020-10-20T02:11:02.677Z)

```
W 2020-10-20T01:08:29Z Readiness probe failed: Get http://10.20.9.3:9600/ready: dial tcp 10.20.9.3:9600: connect: connection refused 
W 2020-10-20T01:10:20Z Readiness probe failed: HTTP probe failed with statuscode: 503 
W 2020-10-20T01:10:31Z {"unmanaged": {"fs.file-max": "65536", "net.ipv4.tcp_fastopen_key": "32726ff6-d365621c-085a7c14-b3770def", "vm.max_map_count": "262144"}} 
W 2020-10-20T01:11:47Z Readiness probe failed: Get http://10.20.10.3:9600/ready: dial tcp 10.20.10.3:9600: connect: connection refused 
W 2020-10-20T01:11:53Z Readiness probe failed: HTTP probe failed with statuscode: 503 
I 2020-10-20T01:12:24Z Node gke-zeebe-cluster-default-pool-1f44de48-bjd0 status is now: NodeNotReady 
I 2020-10-20T01:12:46Z Node gke-zeebe-cluster-default-pool-1f44de48-bjd0 event: DeletingNode 
I 2020-10-20T01:12:49Z Node gke-zeebe-cluster-default-pool-1f44de48-bjd0 event: Removing Node gke-zeebe-cluster-default-pool-1f44de48-bjd0 from Controller 
I 2020-10-20T01:12:50Z Updated load balancer with new hosts 
I 2020-10-20T01:12:51Z successfully exported 2 records to BigQuery 
I 2020-10-20T01:13:02Z AttachVolume.Attach succeeded for volume "pvc-50b8d2b4-8fa2-4084-bb3b-11373cdf0748"  
I 2020-10-20T01:13:05Z AttachVolume.Attach succeeded for volume "pvc-b930d437-9661-4a0e-b957-af57b5667256"  
I 2020-10-20T01:13:10Z Starting kubelet. 
I 2020-10-20T01:13:10Z Node gke-zeebe-cluster-default-pool-1f44de48-bjd0 status is now: NodeHasSufficientMemory 
I 2020-10-20T01:13:10Z Node gke-zeebe-cluster-default-pool-1f44de48-bjd0 status is now: NodeHasNoDiskPressure 
I 2020-10-20T01:13:10Z Node gke-zeebe-cluster-default-pool-1f44de48-bjd0 status is now: NodeHasSufficientPID 
I 2020-10-20T01:13:10Z Node gke-zeebe-cluster-default-pool-1f44de48-bjd0 status is now: NodeHasSufficientMemory 
I 2020-10-20T01:13:10Z Node gke-zeebe-cluster-default-pool-1f44de48-bjd0 status is now: NodeHasNoDiskPressure 
I 2020-10-20T01:13:10Z Node gke-zeebe-cluster-default-pool-1f44de48-bjd0 status is now: NodeHasSufficientPID 
I 2020-10-20T01:13:10Z Updated Node Allocatable limit across pods 
I 2020-10-20T01:13:11Z Node gke-zeebe-cluster-default-pool-1f44de48-bjd0 status is now: NodeHasSufficientMemory 
I 2020-10-20T01:13:11Z Node gke-zeebe-cluster-default-pool-1f44de48-bjd0 status is now: NodeHasNoDiskPressure 
I 2020-10-20T01:13:11Z Node gke-zeebe-cluster-default-pool-1f44de48-bjd0 status is now: NodeHasSufficientPID 
I 2020-10-20T01:13:11Z Node gke-zeebe-cluster-default-pool-1f44de48-bjd0 status is now: NodeHasSufficientMemory 
I 2020-10-20T01:13:11Z Cancelling deletion of Pod release-0-24-4-rc2/worker-54fb9d5f94-gqv7n 
I 2020-10-20T01:13:11Z Cancelling deletion of Pod release-0-25-0/release-0-25-0-zeebe-2 
I 2020-10-20T01:13:11Z Cancelling deletion of Pod dd-test-mem/worker-7f9865f69f-sp2h8 
I 2020-10-20T01:13:11Z Cancelling deletion of Pod release-0-24-4-rc2/release-0-24-4-rc2-zeebe-0 
I 2020-10-20T01:13:11Z Cancelling deletion of Pod release-0-25-0/worker-6bf97dfc5-q8z9v 
I 2020-10-20T01:13:11Z Cancelling deletion of Pod dd-test-mem-8/worker-6c64f4d586-lsxw7 
I 2020-10-20T01:13:11Z Cancelling deletion of Pod dd-test-mem-32-8/worker-9c9d494-lxkxf 
I 2020-10-20T01:13:11Z Cancelling deletion of Pod release-0-24-4-rc2/release-0-24-4-rc2-zeebe-gateway-77b489b5-nc8tp 
I 2020-10-20T01:13:11Z Node gke-zeebe-cluster-default-pool-1f44de48-bjd0 status is now: NodeHasNoDiskPressure 
I 2020-10-20T01:13:11Z Node gke-zeebe-cluster-default-pool-1f44de48-bjd0 status is now: NodeHasSufficientPID 
I 2020-10-20T01:13:11Z Node gke-zeebe-cluster-default-pool-1f44de48-bjd0 status is now: NodeHasSufficientMemory 
I 2020-10-20T01:13:11Z Node gke-zeebe-cluster-default-pool-1f44de48-bjd0 status is now: NodeHasNoDiskPressure 
I 2020-10-20T01:13:11Z Node gke-zeebe-cluster-default-pool-1f44de48-bjd0 status is now: NodeHasSufficientPID 
I 2020-10-20T01:13:11Z Node gke-zeebe-cluster-default-pool-1f44de48-bjd0 status is now: NodeHasSufficientMemory 
I 2020-10-20T01:13:11Z Node gke-zeebe-cluster-default-pool-1f44de48-bjd0 status is now: NodeHasNoDiskPressure 
I 2020-10-20T01:13:11Z Node gke-zeebe-cluster-default-pool-1f44de48-bjd0 status is now: NodeHasSufficientPID 
I 2020-10-20T01:13:11Z Node gke-zeebe-cluster-default-pool-1f44de48-bjd0 status is now: NodeHasSufficientMemory 
I 2020-10-20T01:13:11Z Node gke-zeebe-cluster-default-pool-1f44de48-bjd0 status is now: NodeHasNoDiskPressure 
I 2020-10-20T01:13:11Z Node gke-zeebe-cluster-default-pool-1f44de48-bjd0 status is now: NodeHasSufficientPID 
I 2020-10-20T01:13:11Z Node gke-zeebe-cluster-default-pool-1f44de48-bjd0 status is now: NodeHasSufficientMemory 
I 2020-10-20T01:13:11Z Node gke-zeebe-cluster-default-pool-1f44de48-bjd0 status is now: NodeHasNoDiskPressure 
W 2020-10-20T01:13:11Z network is not ready: runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: kubenet does not have netConfig. This is most likely due to lack of PodCIDR 
W 2020-10-20T01:13:11Z network is not ready: runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: kubenet does not have netConfig. This is most likely due to lack of PodCIDR 
W 2020-10-20T01:13:11Z network is not ready: runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: kubenet does not have netConfig. This is most likely due to lack of PodCIDR 
W 2020-10-20T01:13:11Z network is not ready: runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: kubenet does not have netConfig. This is most likely due to lack of PodCIDR 
W 2020-10-20T01:13:11Z network is not ready: runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: kubenet does not have netConfig. This is most likely due to lack of PodCIDR 
W 2020-10-20T01:13:11Z network is not ready: runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: kubenet does not have netConfig. This is most likely due to lack of PodCIDR 
W 2020-10-20T01:13:11Z network is not ready: runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: kubenet does not have netConfig. This is most likely due to lack of PodCIDR 
W 2020-10-20T01:13:11Z network is not ready: runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: kubenet does not have netConfig. This is most likely due to lack of PodCIDR 
W 2020-10-20T01:13:11Z network is not ready: runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: kubenet does not have netConfig. This is most likely due to lack of PodCIDR 
W 2020-10-20T01:13:12Z MountVolume.SetUp failed for volume "default-token-hv7z9" : failed to sync secret cache: timed out waiting for the condition 
W 2020-10-20T01:13:12Z MountVolume.SetUp failed for volume "default-token-hv7z9" : failed to sync secret cache: timed out waiting for the condition 
I 2020-10-20T01:13:12Z Pulling image "k8s.gcr.io/prometheus-to-sd:v0.8.2" 
I 2020-10-20T01:13:12Z Pulling image "gke.gcr.io/fluent-bit:v1.3.11-gke.0" 
I 2020-10-20T01:13:12Z Container image "gke.gcr.io/kube-proxy-amd64:v1.17.9-gke.1504" already present on machine 
I 2020-10-20T01:13:12Z Created container kube-proxy 
I 2020-10-20T01:13:12Z Pulling image "quay.io/prometheus/node-exporter:v0.18.1" 
I 2020-10-20T01:13:12Z Started container kube-proxy 
I 2020-10-20T01:13:13Z Starting kube-proxy. 
I 2020-10-20T01:13:13Z Successfully pulled image "k8s.gcr.io/prometheus-to-sd:v0.8.2" 
I 2020-10-20T01:13:13Z Created container prometheus-to-sd 
I 2020-10-20T01:13:13Z Started container prometheus-to-sd 
I 2020-10-20T01:13:13Z Pulling image "gcr.io/zeebe-io/worker:zeebe" 
I 2020-10-20T01:13:13Z Pulling image "gcr.io/zeebe-io/zeebe:0.24.4-rc2" 
I 2020-10-20T01:13:14Z Node gke-zeebe-cluster-default-pool-1f44de48-bjd0 event: Registered Node gke-zeebe-cluster-default-pool-1f44de48-bjd0 in Controller 
W 2020-10-20T01:13:15Z Starting containerd container runtime... 
W 2020-10-20T01:13:15Z Starting Docker Application Container Engine... 
W 2020-10-20T01:13:15Z Started Kubernetes kubelet. 
W 2020-10-20T01:13:15Z Starting Docker Application Container Engine... 
I 2020-10-20T01:13:16Z successfully exported 4 records to BigQuery 
I 2020-10-20T01:13:16Z Pulling image "gcr.io/gke-release/gke-metrics-agent:0.1.3-gke.0" 
I 2020-10-20T01:13:16Z Successfully pulled image "gke.gcr.io/fluent-bit:v1.3.11-gke.0" 
I 2020-10-20T01:13:16Z Created container fluentbit 
I 2020-10-20T01:13:16Z Started container fluentbit 
I 2020-10-20T01:13:16Z Pulling image "gke.gcr.io/fluent-bit-gke-exporter:v0.10.2-gke.0" 
I 2020-10-20T01:13:17Z Pulling image "gcr.io/zeebe-io/worker:zeebe" 
I 2020-10-20T01:13:17Z Pulling image "gcr.io/zeebe-io/worker:zeebe" 
I 2020-10-20T01:13:18Z Pulling image "gcr.io/zeebe-io/worker:zeebe" 
I 2020-10-20T01:13:18Z Pulling image "gcr.io/zeebe-io/worker:zeebe" 
I 2020-10-20T01:13:18Z Pulling image "gke.gcr.io/proxy-agent-amd64:v0.0.10-gke.1" 
I 2020-10-20T01:13:18Z Successfully pulled image "quay.io/prometheus/node-exporter:v0.18.1" 
I 2020-10-20T01:13:19Z Created container node-exporter 
I 2020-10-20T01:13:19Z Started container node-exporter 
I 2020-10-20T01:13:23Z Successfully pulled image "gcr.io/zeebe-io/worker:zeebe" 
I 2020-10-20T01:13:24Z Cancelling deletion of Pod release-0-24-4-rc2/release-0-24-4-rc2-zeebe-gateway-77b489b5-nc8tp 
I 2020-10-20T01:13:24Z Cancelling deletion of Pod release-0-24-4-rc2/release-0-24-4-rc2-zeebe-0 
I 2020-10-20T01:13:24Z Cancelling deletion of Pod release-0-25-0/worker-6bf97dfc5-q8z9v 
I 2020-10-20T01:13:24Z Cancelling deletion of Pod release-0-25-0/release-0-25-0-zeebe-2 
I 2020-10-20T01:13:24Z Cancelling deletion of Pod dd-test-mem/worker-7f9865f69f-sp2h8 
I 2020-10-20T01:13:24Z Cancelling deletion of Pod dd-test-mem-8/worker-6c64f4d586-lsxw7 
I 2020-10-20T01:13:24Z Cancelling deletion of Pod release-0-24-4-rc2/worker-54fb9d5f94-gqv7n 
I 2020-10-20T01:13:24Z Cancelling deletion of Pod dd-test-mem-32-8/worker-9c9d494-lxkxf 
I 2020-10-20T01:13:25Z Created container worker 
I 2020-10-20T01:13:25Z Started container worker 
I 2020-10-20T01:13:25Z Pulling image "gcr.io/zeebe-io/zeebe:release-0.25.0" 
I 2020-10-20T01:13:27Z Pulling image "gcr.io/zeebe-io/zeebe:0.24.4-rc2" 
W 2020-10-20T01:13:29Z Readiness probe failed: Get http://10.20.9.3:9600/ready: dial tcp 10.20.9.3:9600: connect: connection refused 
I 2020-10-20T01:13:29Z Successfully pulled image "gcr.io/zeebe-io/zeebe:0.24.4-rc2" 
I 2020-10-20T01:13:30Z Created container zeebe-cluster 
I 2020-10-20T01:13:30Z Started container zeebe-cluster 
I 2020-10-20T01:13:30Z Successfully pulled image "gcr.io/gke-release/gke-metrics-agent:0.1.3-gke.0" 
I 2020-10-20T01:13:31Z Created container gke-metrics-agent 
I 2020-10-20T01:13:31Z Started container gke-metrics-agent 
I 2020-10-20T01:13:31Z Successfully pulled image "gke.gcr.io/fluent-bit-gke-exporter:v0.10.2-gke.0" 
I 2020-10-20T01:13:32Z Created container fluentbit-gke 
I 2020-10-20T01:13:32Z Started container fluentbit-gke 
I 2020-10-20T01:13:32Z Successfully pulled image "gcr.io/zeebe-io/worker:zeebe" 
I 2020-10-20T01:13:32Z Created container worker 
I 2020-10-20T01:13:32Z Started container worker 
I 2020-10-20T01:13:32Z Successfully pulled image "gcr.io/zeebe-io/worker:zeebe" 
I 2020-10-20T01:13:32Z Created container worker 
I 2020-10-20T01:13:32Z Started container worker 
I 2020-10-20T01:13:32Z Successfully pulled image "gcr.io/zeebe-io/worker:zeebe" 
I 2020-10-20T01:13:33Z Created container worker 
I 2020-10-20T01:13:33Z Started container worker 
I 2020-10-20T01:13:33Z Successfully pulled image "gcr.io/zeebe-io/worker:zeebe" 
I 2020-10-20T01:13:33Z Created container worker 
I 2020-10-20T01:13:33Z Started container worker 
I 2020-10-20T01:13:34Z Successfully pulled image "gke.gcr.io/proxy-agent-amd64:v0.0.10-gke.1" 
I 2020-10-20T01:13:34Z Created container konnectivity-agent 
I 2020-10-20T01:13:34Z Started container konnectivity-agent 
I 2020-10-20T01:13:39Z Successfully pulled image "gcr.io/zeebe-io/zeebe:release-0.25.0" 
I 2020-10-20T01:13:40Z Successfully pulled image "gcr.io/zeebe-io/zeebe:0.24.4-rc2" 
I 2020-10-20T01:13:41Z Created container zeebe-cluster 
I 2020-10-20T01:13:41Z Created container zeebe-cluster 
I 2020-10-20T01:13:41Z Started container zeebe-cluster 
I 2020-10-20T01:13:41Z Started container zeebe-cluster 
W 2020-10-20T01:13:42Z Readiness probe failed: Get http://10.0.0.10:9600/ready: dial tcp 10.0.0.10:9600: connect: connection refused 
W 2020-10-20T01:13:46Z Readiness probe failed: Get http://10.0.0.9:9600/ready: dial tcp 10.0.0.9:9600: connect: connection refused 
W 2020-10-20T01:13:52Z Readiness probe failed: HTTP probe failed with statuscode: 503 
W 2020-10-20T01:13:56Z Readiness probe failed: HTTP probe failed with statuscode: 503 
W 2020-10-20T01:14:02Z Readiness probe failed: HTTP probe failed with statuscode: 503 
W 2020-10-20T01:14:06Z Readiness probe failed: HTTP probe failed with statuscode: 503 
W 2020-10-20T01:14:12Z Readiness probe failed: HTTP probe failed with statuscode: 503 
W 2020-10-20T01:14:16Z Readiness probe failed: HTTP probe failed with statuscode: 503 
W 2020-10-20T01:14:22Z Readiness probe failed: HTTP probe failed with statuscode: 503 
W 2020-10-20T01:14:26Z Readiness probe failed: HTTP probe failed with statuscode: 503 
W 2020-10-20T01:14:32Z Readiness probe failed: HTTP probe failed with statuscode: 503 
W 2020-10-20T01:14:36Z Readiness probe failed: HTTP probe failed with statuscode: 503 
W 2020-10-20T01:14:42Z Readiness probe failed: HTTP probe failed with statuscode: 503 
I 2020-10-20T01:14:45Z Updated load balancer with new hosts 
W 2020-10-20T01:14:46Z Readiness probe failed: HTTP probe failed with statuscode: 503 
W 2020-10-20T01:14:52Z Readiness probe failed: HTTP probe failed with statuscode: 503 
W 2020-10-20T01:14:56Z Readiness probe failed: HTTP probe failed with statuscode: 503 
W 2020-10-20T01:15:02Z Readiness probe failed: HTTP probe failed with statuscode: 503 
W 2020-10-20T01:15:06Z Readiness probe failed: HTTP probe failed with statuscode: 503 
W 2020-10-20T01:15:12Z Readiness probe failed: HTTP probe failed with statuscode: 503 
W 2020-10-20T01:15:16Z Readiness probe failed: HTTP probe failed with statuscode: 503 
W 2020-10-20T01:15:20Z Readiness probe failed: HTTP probe failed with statuscode: 503 
W 2020-10-20T01:15:22Z Readiness probe failed: HTTP probe failed with statuscode: 503 
W 2020-10-20T01:15:26Z Readiness probe failed: HTTP probe failed with statuscode: 503 
W 2020-10-20T01:15:32Z Readiness probe failed: HTTP probe failed with statuscode: 503 
W 2020-10-20T01:15:36Z Readiness probe failed: HTTP probe failed with statuscode: 503 
W 2020-10-20T01:15:42Z Readiness probe failed: HTTP probe failed with statuscode: 503 
W 2020-10-20T01:15:46Z Readiness probe failed: HTTP probe failed with statuscode: 503 
W 2020-10-20T01:15:52Z Readiness probe failed: HTTP probe failed with statuscode: 503 
W 2020-10-20T01:15:56Z Readiness probe failed: HTTP probe failed with statuscode: 503 
W 2020-10-20T01:16:02Z Readiness probe failed: HTTP probe failed with statuscode: 503 
W 2020-10-20T01:16:06Z Readiness probe failed: HTTP probe failed with statuscode: 503 
W 2020-10-20T01:16:12Z Readiness probe failed: HTTP probe failed with statuscode: 503 
W 2020-10-20T01:16:16Z Readiness probe failed: HTTP probe failed with statuscode: 503 
W 2020-10-20T01:16:22Z Readiness probe failed: HTTP probe failed with statuscode: 503 
W 2020-10-20T01:16:26Z Readiness probe failed: HTTP probe failed with statuscode: 503 
W 2020-10-20T01:16:32Z Readiness probe failed: HTTP probe failed with statuscode: 503 
W 2020-10-20T01:16:36Z Readiness probe failed: HTTP probe failed with statuscode: 503 
W 2020-10-20T01:16:42Z Readiness probe failed: HTTP probe failed with statuscode: 503 
W 2020-10-20T01:16:46Z Readiness probe failed: HTTP probe failed with statuscode: 503 
W 2020-10-20T01:16:47Z Readiness probe failed: Get http://10.20.10.3:9600/ready: dial tcp 10.20.10.3:9600: connect: connection refused 
W 2020-10-20T01:16:52Z Readiness probe failed: HTTP probe failed with statuscode: 503 
W 2020-10-20T01:16:53Z Readiness probe failed: HTTP probe failed with statuscode: 503 
W 2020-10-20T01:16:56Z Readiness probe failed: HTTP probe failed with statuscode: 503 
W 2020-10-20T01:18:16Z Readiness probe failed: HTTP probe failed with statuscode: 503 
W 2020-10-20T01:18:22Z Readiness probe failed: HTTP probe failed with statuscode: 503 
W 2020-10-20T01:18:29Z Readiness probe failed: Get http://10.20.9.3:9600/ready: dial tcp 10.20.9.3:9600: connect: connection refused 
W 2020-10-20T01:20:20Z Readiness probe failed: HTTP probe failed with statuscode: 503 
W 2020-10-20T01:21:47Z Readiness probe failed: Get http://10.20.10.3:9600/ready: dial tcp 10.20.10.3:9600: connect: connection refused 
```

**Comment by Zelldon** [comment]
The release 0.24.4.rc2 gateway has no topology.

```
[zell zeebe/ ns:release-0-24-4-rc2]$ kgpo
NAME                                              READY   STATUS      RESTARTS   AGE
curator-1603162800-5z9dc                          0/1     Completed   0          15h
elasticsearch-master-0                            1/1     Running     0          7d2h
elasticsearch-master-1                            1/1     Running     0          7d2h
elasticsearch-master-2                            1/1     Running     0          7d2h
release-0-24-4-rc2-zeebe-0                        0/1     Running     0          7d2h
release-0-24-4-rc2-zeebe-1                        1/1     Running     0          7d2h
release-0-24-4-rc2-zeebe-2                        0/1     Running     0          7d2h
release-0-24-4-rc2-zeebe-gateway-77b489b5-nc8tp   1/1     Running     0          7d2h
starter-6996966698-bb7h7                          1/1     Running     0          6d10h
worker-54fb9d5f94-4z7rr                           1/1     Running     0          7d2h
worker-54fb9d5f94-5kzcb                           1/1     Running     0          7d2h
worker-54fb9d5f94-8h858                           1/1     Running     0          32h
worker-54fb9d5f94-c5pwk                           1/1     Running     0          45h
worker-54fb9d5f94-fqrht                           1/1     Running     0          7d2h
worker-54fb9d5f94-gqv7n                           1/1     Running     0          7d2h
worker-54fb9d5f94-k2zqb                           1/1     Running     0          7d2h
worker-54fb9d5f94-klhtl                           1/1     Running     0          7d2h
worker-54fb9d5f94-lc7tq                           1/1     Running     0          7d2h
worker-54fb9d5f94-lqd6c                           1/1     Running     0          7d2h
worker-54fb9d5f94-p8v4w                           1/1     Running     0          7d2h
worker-54fb9d5f94-qrqhl                           1/1     Running     0          6d4h
[zell zeebe/ ns:release-0-24-4-rc2]$ k exec -it release-0-24-4-rc2-zeebe-gateway-77b489b5-nc8tp -- bash
root@release-0-24-4-rc2-zeebe-gateway-77b489b5-nc8tp:/usr/local/zeebe# zbctl status --insecure
Cluster size: 3
Partitions count: 3
Replication factor: 3
Gateway version: 0.24.4
Brokers:
```

**Comment by deepthidevaki** [comment]
There are two things in play:

1. Can the infrastructure prevent two nodes from different namespaces from communicating with each other? 
2. Can zeebe detects it's receiving messages from the nodes outside of its cluster? 
   NettyMessagingService uses the cluster name to calculate a preamble, which is used to validate a connection. So, in theory, as long as the clusternames are unique, it should be fine. https://github.com/zeebe-io/zeebe/blob/d7646c02ea3e351e704e02f8889646b521ba9cb7/atomix/cluster/src/main/java/io/atomix/cluster/messaging/impl/NettyMessagingService.java#L107
However, we observed that swim might not be using this. So it is able to communicate to nodes outside of its cluster. That is why gateway could recieve topology from other namespace. We still have to figure out what really happened with raft communications.

**Comment by Zelldon** [comment]
See related discussion in slack https://camunda.slack.com/archives/CT702EPFH/p1603275101002200

**Comment by npepinpe** [comment]
As discussed, let's add the cluster name check on all communications (unicast and messaging), and add docs to recommend users add a NetworkPolicy crd to prevent inter namespace comms

**Comment by korthout** [comment]
This is also happening on my baseline benchmark of 0.25.0: http://34.77.165.228/d/I4lo7_EZk/zeebe?orgId=1&from=now-2d&to=now&var-DS_PROMETHEUS=Prometheus&var-namespace=korthout-0-25-0-baseline&var-pod=All&var-partition=All 

```
root@korthout-0-25-0-baseline-zeebe-gateway-668b9f8dcb-9j4gk:/usr/local/zeebe# bin/zbctl --insecure status
Cluster size: 3
Partitions count: 3
Replication factor: 3
Gateway version: 0.25.0
Brokers:
  Broker 0 - korthout-0-25-0-baseline-zeebe-0.korthout-0-25-0-baseline-zeebe.korthout-0-25-0-baseline.svc.cluster.local:26501
    Version: 0.25.0
    Partition 1 : Leader
    Partition 2 : Follower
    Partition 3 : Leader
  Broker 2 - release-0-24-4-rc2-zeebe-2.release-0-24-4-rc2-zeebe.release-0-24-4-rc2.svc.cluster.local:26501
    Version: 0.24.4
    Partition 1 : Follower
    Partition 2 : Follower
    Partition 3 : Follower
```

**Comment by Zelldon** [comment]
OMG :scream: @npepinpe we should fix this :eyes:

**Comment by npepinpe** [comment]
I'm still not convinced this is primarily an issue with our deployments, as we've never seen this in Camunda Cloud, hence why I wouldn't bump the priority further, but we should still fix it of course.

**Comment by Zelldon** [comment]
I checked together with @deepthidevaki last week and today again with @Faffnir whether we can access inside a pod another pod from another namespace.

Yes it is possible via domain names but also via ip's.


```sh
root@zell-kw-48-benchmark-zeebe-gateway-8658576467-hrgzf:/usr/local/zeebe# curl zell-kw-44-benchmark-zeebe-0.zell-kw-44-benchmark-zeebe.zell-kw-44-benchmark.svc.cluster.local:9600/metrics
# HELP tomcat_sessions_active_current_sessions  
# TYPE tomcat_sessions_active_current_sessions gauge
tomcat_sessions_active_current_sessions 0.0
# HELP atomix_partition_raft_commit_index The commit index
# TYPE atomix_partition_raft_commit_index gauge
atomix_partition_raft_commit_index{partitionGroupName="raft",partition="1",} 2.467666941E9
# ...
```

**Comment by deepthidevaki** [comment]
I had a look at this issue. The main problem is the NettyUnicastService does not have any check in place to detect if it is receiving messages from a valid node. NettyMessagingService uses a preamble to detect messages received from nodes outside of its cluster. The preamble is generated from the clusterId which should be unique. If the preamble of the received message does not matches the preamble of this cluster, it simply rejects the message. This is were we see the invalid handshake error messages.

Swim uses NettyUnicastService for gossip. Raft and other communications with in the cluster uses NettyMessagingService. So if this happens we can guarantee that data is not corrupted because raft will not accept messages from wrong leaders. However since Swim communicates to the wrong nodes, the membership information has now wrong ip/host names. 

Possible solutions are 
1. Remove NettyUnicastService and use NettyMessagingService instead.
2. Use the preamble in NettyUnicastService similar to the messaging service.

Removing NettyUnicastService is probably not a good idea. It uses UDP for sending messages which makes perfect sense for gossip messages because it doesn't require reliable communication. If we use NettyMessagingService for the gossip, it would have to establish a new tcp connection for each message.

So my proposal is to use the preamble in NettyUnicastService. It is an easy and quick fix. Note that it is not fixing the infra configuration. But just ensures that if in case the resolved ips are wrong, the cluster would not reach an inconsistent state. 

wdyt? @Zelldon @npepinpe @MiguelPires

**Comment by npepinpe** [comment]
Sounds good to me. Would be good to document this - if you want to deploy multiple Zeebe clusters in the same network, make sure to give them different cluster names to avoid inter-cluster communication.

**Comment by nyarly** [comment]
Sorry to pester you, @npepinpe, but we just observed this behavior in a, 8.1.3 cluster deployed with the Helm chart.

**Comment by Zelldon** [comment]
@nyarly you can define Networks policies in kubernetes to avoid such cases https://kubernetes.io/docs/concepts/security/multi-tenancy/#network-isolation

Did you look at that already? 

Hope that helps.

**Comment by nyarly** [comment]
@Zelldon I appreciate the advice. We're already looking into that approach. What doesn't make sense to me is that the brokers (or gateway?) would accidentally connect to one another in the first place. The brokers use their initial contacts and get FQDNs.

In part, it would help to have a better sense of how the components discover each other in the first place. I wasn't able to find anything in the docs.

**Comment by Zelldon** [comment]
@nyarly what we have seen in our Benchmarks from time to time is that kubernetes reuse IP's so if a node goes down likely the ip will be assigned to new node/pods etc. The issue is that if the gateway or broker has still cached that IP and connects to it.

Maybe you can check whether this also happened in your case as well.

**Comment by Zelldon** [comment]
Related issue which we have fixed recently https://github.com/camunda/zeebe/pull/11307

Might be worth to upgrade to a newer version.
